---
services:

  alpine:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.alpine
    volumes:
      - ./input:/tmp/input
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - AWS_REGION
      - AWS_DEFAULT_REGION=us-east-1

  debian:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - ./input:/tmp/input
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - AWS_REGION
      - AWS_DEFAULT_REGION=us-east-1

  debian.backport:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.debian.backport
    volumes:
      - ./input:/tmp/input
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - AWS_REGION
      - AWS_DEFAULT_REGION=us-east-1
